const names=Object.keys(KITS), aliases={bayern:'Bayern Munchen 2026/2027','بایرن':'Bayern Munchen 2026/2027',psg:'PSG 2027','پاریس':'PSG 2027',inter:'Inter Milan 2026/2027','اینتر':'Inter Milan 2026/2027',barca:'Barcelona 2026/2027','بارسا':'Barcelona 2026/2027',real:'Real Madrid 2026/2027','رئال':'Real Madrid 2026/2027',milan:'AC Milan 2026/2027'};
const $=id=>document.getElementById(id); const labels=(t,i)=>(KIT_LABELS[t]||[])[i]||'کیت';
function totalKits(){return names.reduce((n,t)=>n+KITS[t].length,0)}
function init(){
 $('stats').innerHTML=`<div class="stat"><b>${names.length}</b><span>تیم فعال</span></div><div class="stat"><b>${totalKits()}</b><span>کیت موجود</span></div><div class="stat"><b>2019</b><span>نسخه DLS</span></div>`;
 renderTeams();renderLatest();renderMenu();route();
 $('menuBtn').onclick=toggleMenu;$('overlay').onclick=closeMenu;$('searchInput').addEventListener('input',()=>renderSearch($('searchInput').value));$('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});$('aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendAI()});
}
function toggleMenu(){const open=$('drawer').classList.toggle('open');$('overlay').classList.toggle('show',open);$('menuBtn').setAttribute('aria-expanded',open)}function closeMenu(){$('drawer').classList.remove('open');$('overlay').classList.remove('show');$('menuBtn').setAttribute('aria-expanded','false')}
function renderMenu(){$('teamList').innerHTML=names.map(n=>`<button class="team-mini" onclick="openTeam(${JSON.stringify(n)});closeMenu()"><span>${TEAM_META[n]?.[1]||'⚽'}</span><span>${TEAM_META[n]?.[0]||n}</span><small>${KITS[n].length} کیت</small></button>`).join('')}
function renderTeams(){$('teamCards').innerHTML=names.map(n=>{const m=TEAM_META[n]||[n,'⚽','DLS'];return `<button class="team-card" onclick="openTeam(${JSON.stringify(n)})"><div class="team-icon">${m[1]}</div><div><strong>${m[0]}</strong><span>${m[2]} • ${n.match(/\d{4}\/\d{4}|\d{4}/)?.[0]||''}</span></div><b>→</b></button>`}).join('')}
function renderLatest(){const picks=[['PSG 2027',0],['Bayern Munchen 2026/2027',0],['Inter Milan 2026/2027',0],['AC Milan 2026/2027',0],['Barcelona 2026/2027',0],['Real Madrid 2026/2027',0]];$('latestGrid').innerHTML=picks.map(([t,i])=>kitCard(t,i)).join('')}
function kitCard(t,i){const u=KITS[t][i];return `<article class="kit-card"><div class="kit-image"><img src="${u}" loading="lazy" alt="${labels(t,i)} ${t}" onerror="this.classList.add('broken')"><span>${labels(t,i)}</span></div><div class="kit-info"><strong>${TEAM_META[t]?.[0]||t}</strong><small>${labels(t,i)} • DLS 2019</small><div class="card-actions"><button onclick="copyLink(${JSON.stringify(u)},this)">کپی لینک</button><a href="${u}" target="_blank" rel="noopener">PNG ↗</a></div></div></article>`}
function openTeam(t){hideViews();$('teamView').classList.add('active');const m=TEAM_META[t]||[t,'⚽','DLS'];$('teamHero').innerHTML=`<div class="team-hero"><div class="team-bigicon">${m[1]}</div><div><span>${m[2]}</span><h1>${m[0]}</h1><p>${t.includes('2027')?'فصل 2026/27':'فصل 2026/27'} • ${KITS[t].length} کیت</p></div></div><div class="kit-filter"><button class="filter active" onclick="filterTeam('all',this)">همه</button><button class="filter" onclick="filterTeam('kit',this)">کیت‌ها</button><button class="filter" onclick="filterTeam('gk',this)">گلرها</button></div>`;$('teamKits').innerHTML=KITS[t].map((_,i)=>kitCard(t,i)).join('');$('teamKits').dataset.team=t;location.hash='team='+encodeURIComponent(t)}
function filterTeam(type,btn){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const t=$('teamKits').dataset.team;[...$('teamKits').children].forEach((c,i)=>{const g=labels(t,i).includes('گلر');c.style.display=type==='all'||(type==='gk'&&g)||(type==='kit'&&!g)?'':'none'})}
function openSearch(){hideViews();$('searchView').classList.add('active');location.hash='search';$('searchInput').focus();renderSearch($('searchInput').value)}function runSearch(){renderSearch($('searchInput').value)}
function renderSearch(q){const term=(q||'').trim().toLowerCase();const exact=aliases[term]||term;let out=[];names.forEach(t=>KITS[t].forEach((u,i)=>{const text=(t+' '+labels(t,i)+' '+(TEAM_META[t]?.[0]||'')).toLowerCase();if(!exact||text.includes(exact))out.push(kitCard(t,i))}));$('searchResults').innerHTML=out.length?out.join(''):`<div class="empty">کیتی با «${escapeHtml(q)}» پیدا نشد.</div>`}
function openGuide(){hideViews();$('guideView').classList.add('active');location.hash='guide'}function hideViews(){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'))}function goHome(){hideViews();$('home').classList.add('active');history.replaceState(null,'',location.pathname+location.search);closeMenu();window.scrollTo({top:0,behavior:'smooth'})}
function copyLink(u,b){navigator.clipboard?.writeText(u).catch(()=>fallbackCopy(u));if(!navigator.clipboard)fallbackCopy(u);b.textContent='کپی شد ✓';b.classList.add('done');toast('لینک کپی شد ✓');setTimeout(()=>{b.textContent='کپی لینک';b.classList.remove('done')},1400)}function fallbackCopy(u){const x=document.createElement('textarea');x.value=u;document.body.appendChild(x);x.select();document.execCommand('copy');x.remove()}function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function addMsg(t,c){const d=document.createElement('div');d.className='msg '+c;d.textContent=t;$('chat').appendChild(d);$('chat').scrollTop=$('chat').scrollHeight}function askAI(q){if(!q)return;addMsg(q,'user');setTimeout(()=>addMsg(aiAnswer(q),'bot'),180)}function sendAI(){const i=$('aiInput');const q=i.value.trim();i.value='';askAI(q)}function aiAnswer(q){const x=q.toLowerCase();if(x.includes('psg')||x.includes('پاریس'))return'برای PSG 2027 وارد منوی تیم‌ها شو یا در جستجو PSG را بنویس. پنج کیت فعلی نمایش داده می‌شوند.';if(x.includes('کپی')||x.includes('لینک'))return'روی «کپی لینک» در کارت هر کیت بزن. لینک PNG در کلیپ‌بورد ذخیره می‌شود.';if(x.includes('نصب')||x.includes('وارد'))return'لینک PNG کیت را کپی کن و در بخش دریافت/ویرایش کیت DLS 2019 بازی، لینک تصویر را وارد کن.';if(x.includes('بایرن')||x.includes('bayern'))return'بایرن در سایت با نام Bayern Munchen 2026/2027 قرار دارد و فعلاً چهار کیت برای آن ثبت شده است.';if(x.includes('بارسا')||x.includes('barca')||x.includes('barcelona'))return'Barcelona 2026/2027 را از منوی تیم‌ها انتخاب کن؛ هفت کیت فعلی آن نمایش داده می‌شود.';if(x.includes('اینتر')||x.includes('inter'))return'Inter Milan 2026/2027 در منوی تیم‌ها قرار دارد و شش کیت فعلی دارد.';if(x.includes('کیت')||x.includes('تیم'))return'از منوی تیم‌ها یک باشگاه را انتخاب کن یا از جستجو نام تیم و نوع کیت را وارد کن.';return'سؤالت را دقیق‌تر بنویس؛ مثلاً «کیت PSG کجاست؟» یا «چطور لینک را کپی کنم؟»'}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function route(){const h=decodeURIComponent(location.hash);if(h.startsWith('#team=')){const t=h.slice(6);if(KITS[t])return openTeam(t)}if(h==='#search')return openSearch();if(h==='#guide')return openGuide();goHome()}window.addEventListener('hashchange',route);init();
